POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx5bngiLCJpZCI6MiwiaWF0IjoxNjMzOTYxOTY4fQ.176gUskMbCEo02QMxqZjFlymzv_GQtIQajHCbXJVX1Q

{
  "content": "Expo is a must in React Native development",
  "important": true
}